// Her ülke için: birincil deprem kaynağı + bounding box + görüntüleme bilgisi
// USGS her zaman ek kaynak olarak çalışır; burada ülkeye özel kaynak tanımlanır.

export const COUNTRY_CONFIGS = {
  TR: {
    code: 'TR',
    name: 'Türkiye',
    flag: '🇹🇷',
    sourceKey: 'kandilli',
    sourceLabel: 'Kandilli + USGS',
    defaultCity: 'İstanbul',
    defaultLanguage: 'tr',
    bounds: { minLat: 34.5, maxLat: 43.5, minLon: 25.0, maxLon: 45.5 },
    emergencyNumbers: [
      { label: 'AFAD', value: '122' },
      { label: 'Acil', value: '112' },
      { label: 'Alo Deprem', value: '184' },
    ],
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    sourceKey: 'jma',
    sourceLabel: 'JMA (P2PQuake) + USGS',
    defaultCity: 'Tokyo',
    defaultLanguage: 'ja',
    bounds: { minLat: 24.0, maxLat: 46.0, minLon: 122.0, maxLon: 154.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '119' },
      { label: 'Police', value: '110' },
      { label: 'JMA Info', value: '117' },
    ],
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    sourceKey: 'ingv',
    sourceLabel: 'INGV + USGS',
    defaultCity: 'Roma',
    defaultLanguage: 'en',
    bounds: { minLat: 36.0, maxLat: 48.0, minLon: 6.0, maxLon: 20.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '112' },
      { label: 'Fire', value: '115' },
      { label: 'Ambulance', value: '118' },
    ],
  },
  GR: {
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    sourceKey: 'noa',
    sourceLabel: 'NOA + USGS',
    defaultCity: 'Athens',
    defaultLanguage: 'en',
    bounds: { minLat: 34.0, maxLat: 42.0, minLon: 19.0, maxLon: 30.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '112' },
      { label: 'Fire', value: '199' },
      { label: 'Ambulance', value: '166' },
    ],
  },
  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    sourceKey: 'geonet',
    sourceLabel: 'GeoNet + USGS',
    defaultCity: 'Wellington',
    defaultLanguage: 'en',
    bounds: { minLat: -48.0, maxLat: -34.0, minLon: 165.0, maxLon: 180.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '111' },
      { label: 'Civil Defence', value: '0800555000' },
    ],
  },
  ID: {
    code: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    sourceKey: 'bmkg',
    sourceLabel: 'BMKG + USGS',
    defaultCity: 'Jakarta',
    defaultLanguage: 'en',
    bounds: { minLat: -12.0, maxLat: 8.0, minLon: 95.0, maxLon: 141.0 },
    emergencyNumbers: [
      { label: 'BNPB', value: '117' },
      { label: 'Emergency', value: '112' },
      { label: 'Ambulance', value: '119' },
    ],
  },
  US: {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    sourceKey: 'usgs',
    sourceLabel: 'USGS',
    defaultCity: 'Los Angeles',
    defaultLanguage: 'en',
    bounds: { minLat: 24.0, maxLat: 50.0, minLon: -125.0, maxLon: -65.0 },
    emergencyNumbers: [
      { label: '911', value: '911' },
      { label: 'FEMA', value: '18006213362' },
    ],
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Santiago',
    defaultLanguage: 'en',
    bounds: { minLat: -56.0, maxLat: -17.0, minLon: -76.0, maxLon: -65.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '132' },
      { label: 'Police', value: '133' },
      { label: 'Ambulance', value: '131' },
    ],
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Mexico City',
    defaultLanguage: 'en',
    bounds: { minLat: 14.0, maxLat: 33.0, minLon: -118.0, maxLon: -86.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '911' },
      { label: 'CENAPRED', value: '8008004899' },
    ],
  },
  IR: {
    code: 'IR',
    name: 'Iran',
    flag: '🇮🇷',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Tehran',
    defaultLanguage: 'en',
    bounds: { minLat: 24.0, maxLat: 40.0, minLon: 44.0, maxLon: 64.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '115' },
      { label: 'Police', value: '110' },
      { label: 'Fire', value: '125' },
    ],
  },
  PH: {
    code: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Manila',
    defaultLanguage: 'en',
    bounds: { minLat: 4.0, maxLat: 22.0, minLon: 116.0, maxLon: 128.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '911' },
      { label: 'PHIVOLCS', value: '117' },
    ],
  },
  PE: {
    code: 'PE',
    name: 'Peru',
    flag: '🇵🇪',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Lima',
    defaultLanguage: 'en',
    bounds: { minLat: -20.0, maxLat: 0.0, minLon: -82.0, maxLon: -68.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '911' },
      { label: 'Police', value: '105' },
      { label: 'Fire', value: '116' },
    ],
  },
  AF: {
    code: 'AF',
    name: 'Afghanistan',
    flag: '🇦🇫',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Kabul',
    defaultLanguage: 'en',
    bounds: { minLat: 29.0, maxLat: 39.0, minLon: 60.0, maxLon: 75.0 },
    emergencyNumbers: [
      { label: 'Police', value: '119' },
      { label: 'Ambulance', value: '102' },
    ],
  },
  RO: {
    code: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    sourceKey: 'usgs-bbox',
    sourceLabel: 'USGS',
    defaultCity: 'Bucharest',
    defaultLanguage: 'en',
    bounds: { minLat: 43.0, maxLat: 48.5, minLon: 20.0, maxLon: 30.0 },
    emergencyNumbers: [
      { label: 'Emergency', value: '112' },
      { label: 'INFP', value: '021164' },
    ],
  },
};

export const COUNTRY_LIST = Object.values(COUNTRY_CONFIGS);

export const getCountryConfig = (code) =>
  COUNTRY_CONFIGS[code] || COUNTRY_CONFIGS.TR;
