export const DATA_ATTRIBUTION_SOURCES = [
  {
    id: 'usgs',
    name: 'USGS Earthquake Hazards Program',
    category: 'Deprem verisi',
    attribution: 'U.S. Geological Survey',
    usage: 'ABD ve global deprem katalogları için kullanılır. USGS kaynak gösterimi korunmalıdır.',
    license: 'USGS üretimi veriler genel olarak ABD kamu malıdır; USGS uygun atıf ister.',
    url: 'https://earthquake.usgs.gov/fdsnws/event/1/',
  },
  {
    id: 'kandilli',
    name: 'Kandilli Rasathanesi / BDTIM',
    category: 'Deprem verisi',
    attribution: 'Bogazici University Kandilli Observatory and Earthquake Research Institute',
    usage: 'Türkiye deprem kayıtları için birincil kaynak olarak kullanılır.',
    license: 'Resmi kaynak adı görünür tutulmalı; veriler bilgilendirme amaçlı gösterilmelidir.',
    url: 'http://www.koeri.boun.edu.tr/scripts/lst0.asp',
  },
  {
    id: 'ingv',
    name: 'INGV FDSN Event Web Service',
    category: 'Deprem verisi',
    attribution: 'Istituto Nazionale di Geofisica e Vulcanologia',
    usage: 'İtalya deprem kayıtları için kullanılır.',
    license: 'INGV kaynak gösterimi ve sağlayıcı kullanım şartları korunmalıdır.',
    url: 'https://webservices.ingv.it/fdsnws/event/1/',
  },
  {
    id: 'jma-p2pquake',
    name: 'JMA / P2PQuake',
    category: 'Deprem verisi',
    attribution: 'Japan Meteorological Agency, via P2PQuake JSON API',
    usage: 'Japonya deprem kayıtları için P2PQuake API üzerinden kullanılır.',
    license: 'JMA içerikleri kaynak gösterimi gerektirir; P2PQuake servis adı da korunmalıdır.',
    url: 'https://www.p2pquake.net/develop/json_api_v2/',
  },
  {
    id: 'geonet',
    name: 'GeoNet / GNS Science',
    category: 'Deprem verisi',
    attribution: 'GeoNet, GNS Science, Earthquake Commission and LINZ',
    usage: 'Yeni Zelanda deprem kayıtları için kullanılır.',
    license: 'GeoNet veri politikası ve disclaimer koşulları geçerlidir.',
    url: 'https://api.geonet.org.nz/',
  },
  {
    id: 'bmkg',
    name: 'BMKG Data Gempabumi',
    category: 'Deprem verisi',
    attribution: 'Badan Meteorologi, Klimatologi, dan Geofisika',
    usage: 'Endonezya deprem kayıtları için kullanılır.',
    license: 'BMKG kaynak gösterimi ve resmi veri kullanım koşulları korunmalıdır.',
    url: 'https://data.bmkg.go.id/gempabumi/',
  },
  {
    id: 'gem-openquake',
    name: 'GEM / OpenQuake',
    category: 'Sismik tehlike haritası',
    attribution: 'Global Earthquake Model Foundation / OpenQuake',
    usage: 'Haritadaki bölgesel sismik tehlike katmanı ve risk skorunda kullanılır.',
    license: 'GEM/OpenQuake atıf ve ürün lisans koşulları korunmalıdır.',
    url: 'https://www.globalquakemodel.org/product/openquake-engine/',
  },
  {
    id: 'vs30',
    name: 'Global Vs30 Models and Data',
    category: 'Zemin verisi',
    attribution: 'USGS Vs30 models and related global Vs30 datasets',
    usage: 'Haritada uzun basılan nokta için zemin sınıfı/Vs30 tahmini üretir.',
    license: 'Kullanılan Vs30 raster dosyasının sağlayıcı lisansı ve atıf koşulları korunmalıdır.',
    url: 'https://earthquake.usgs.gov/data/vs30/',
  },
  {
    id: 'faults',
    name: 'GEM Active Faults Dataset',
    category: 'Fay verisi',
    attribution: 'Global Earthquake Model Foundation active faults data',
    usage: 'Fay mesafesi ve sismik risk bileşenleri için server tarafında kullanılır.',
    license: 'GEM veri seti lisansı ve atıf koşulları korunmalıdır.',
    url: 'https://www.globalquakemodel.org/',
  },
];
